
name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: |
          echo $GITHUB_ACTOR,
          echo "$GITHUB_ACTOR"

      - name: Run a multi-line script
        if: github.actor == 'nrraphael'
        run: |
          echo $GITHUB_ACTOR,
          echo "$GITHUB_ACTOR"
